---
# Common setup tasks for all products

- name: Create temporary directory
  file:
    path: /tmp/percona_build
    state: directory
    mode: '0755'

- name: Install Common Development Tools (RedHat)
  when: os_type == "rpm"
  yum:
    name:
      - wget
      - sudo
      - git
      - make
      - cmake
      - gcc
      - gcc-c++
    state: present

- name: Install Common Development Tools (Debian)
  when: os_type == "deb"
  apt:
    name:
      - wget
      - sudo
      - git
      - make
      - cmake
      - gcc
      - g++
      - curl
    state: present
