---
# Ansible playbook to install dependencies required for Percona products build
# Supports multiple product types and versions

- name: Install Percona Product Build Dependencies
  hosts: "{{ target_host | default('localhost') }}"
  become: yes
  vars:
    go_version: "1.22.4"
    mongodb_toolchain_url: "https://downloads.percona.com/downloads/TESTING/issue-CUSTO83"
    fipsmode: 0
    product: "{{ product | default('PSMDB') }}"
    version: "{{ version | default('70') }}"
    custom_user: "{{ lookup('env', 'USER') | default('root') }}"

  tasks:
    - name: Gather OS facts
      setup:
        gather_subset: 
          - '!all'
          - '!min'
          - 'distribution'
          - 'hardware'
          
    - name: Set Debian/Ubuntu variables
      when: ansible_os_family == "Debian"
      set_fact:
        os_type: "deb"
        os_name: "{{ ansible_distribution_release }}"
        arch: "{{ ansible_architecture }}"
        
    - name: Set RedHat/CentOS variables
      when: ansible_os_family == "RedHat"
      set_fact:
        os_type: "rpm"
        os_name: "el{{ ansible_distribution_major_version }}"
        rhel_version: "{{ ansible_distribution_major_version }}"
        arch: "{{ 'i386' if ansible_architecture == 'i686' else ansible_architecture }}"

    # === Common tasks for all OS types ===
    - name: Create temporary directory
      file:
        path: /tmp/percona_build
        state: directory
        mode: '0755'

    # Display product and version information
    - name: Display build configuration
      debug:
        msg: "Building environment for {{ product }}-{{ version }} on {{ os_type }} {{ os_name }} ({{ arch }})"

    # === Common tasks for all products ===
    - name: Include common setup tasks
      include_tasks: tasks/common_setup.yml

    # === Product-specific tasks ===
    - name: Include PSMDB setup tasks
      include_tasks: tasks/psmdb_setup.yml
      when: product == "PSMDB"

    - name: Include PS setup tasks
      include_tasks: tasks/ps_setup.yml
      when: product == "PS"

    - name: Include PXB setup tasks
      include_tasks: tasks/pxb_setup.yml
      when: product == "PXB"

    - name: Include PXC setup tasks
      include_tasks: tasks/pxc_setup.yml
      when: product == "PXC"

    # === Final cleanup ===
    - name: Clean up temporary files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/percona_build
      ignore_errors: yes
